
# Feature branch settings
action = "create" # Options: create / delete
feature_name = "feature/pg/MyLocalFeatureCreation01"
#feature_name = "feature/[Initials]/[FeatureName]"

#region Feature branch setup script
import json, os, sys, jwt
from datetime import datetime

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
sys.path.append(os.getcwd())

import modules.auth_functions as authfunc, modules.azure_functions as azfunc, modules.fabric_functions as fabfunc, modules.devops_functions as devopsfunc

start_time = datetime.now()

credential = authfunc.create_credentials_from_user()
vault_upn_token = credential.get_token("https://vault.azure.net/.default").token
management_upn_token = credential.get_token("https://management.core.windows.net/.default").token
devops_token = credential.get_token("499b84ac-1321-427f-aa17-267ca6975798/.default").token
fabric_upn_token = credential.get_token("https://api.fabric.microsoft.com/.default").token

decoded_token = jwt.decode(vault_upn_token, options={"verify_signature": False})

setup_file_path = os.path.join(os.path.dirname(__file__), f'fabric_setup.json')

if os.path.exists(setup_file_path):
    with open(setup_file_path, 'r') as file:
        data = json.load(file)

        dev_env_name = data.get("feature_name")
        default_capacity_id = data.get("capacity_id")
        stages = data.get("stages")
        key_vault_name = data.get("key_vault_name")

        git_settings = data.get("git_integration")

        tenant_id = azfunc.get_keyvault_secret(vault_upn_token, key_vault_name, "TenantId")
        app_id = azfunc.get_keyvault_secret(vault_upn_token, key_vault_name, "Fabric-SPN-ClientID")
        app_secret = azfunc.get_keyvault_secret(vault_upn_token, key_vault_name, "Fabric-SPN-Secret")

        fabric_access_token = authfunc.get_access_token(tenant_id, app_id, app_secret, 'https://api.fabric.microsoft.com')

        if action == "create":
            print(f"############################## Setting up development environment ##############################")
            
            devopsfunc.create_branch(
                devops_token, 
                git_settings.get("DevOpsOrgName"), 
                git_settings.get("DevOpsProjectName"),
                git_settings.get("DevOpsRepoName"),
                git_settings.get("DevOpsDefaultBranch"),
                feature_name)

            for stage, stage_props in stages.items():
                workspace_name = dev_env_name.format(feature_name=feature_name.replace("feature/",""), stage=stage)

                current_time_utc = datetime.now().strftime("%Y-%m-%d %H:%M:%S (UTC)")
                workspace_desc = (
                    f"Feature workspace auto-generated by script: {current_time_utc}\n\n"
                    f"Organization: {git_settings.get("DevOpsOrgName")}\n"
                    f"Project: {git_settings.get("DevOpsProjectName")}\n"
                    f"Repository: {git_settings.get("DevOpsRepoName")}\n"
                    f"Branch: {feature_name}\n"
                    f"Responsible: {decoded_token.get("name")} ({decoded_token.get("upn")})"
                )
                
                workspace = fabfunc.create_workspace(fabric_access_token, workspace_name, workspace_desc)
                workspace_id = workspace.get("id")

                fabfunc.assign_workspace_to_capacity(fabric_access_token, workspace_id, default_capacity_id)
                fabfunc.add_workspace_user(fabric_access_token, workspace_id, "Admin", "User", decoded_token.get("upn"))

                if not stage_props.get("private_endpoints") is None:
                    for private_endpoint in stage_props.get("private_endpoints"):
                        fabfunc.create_workspace_managed_private_endpoint(fabric_access_token, workspace_id, private_endpoint.get("name"), private_endpoint.get("id"))
                        if(private_endpoint.get("auto_approve")):
                            management_access_token = authfunc.get_access_token(tenant_id, app_id, app_secret, 'https://management.core.windows.net')
                            connection_name = f"{workspace_id}.{private_endpoint.get("name")}-"
                            pe_connection = azfunc.get_private_endpoint_by_name(management_access_token, private_endpoint.get("id"), connection_name)                        
                            azfunc.approve_private_endpoint(management_access_token, private_endpoint.get("id"), pe_connection.get("name"))    

                if not git_settings is None and fabric_access_token:
                    print (f"Setting up Git integration for workspace {workspace_name} connection to feature {feature_name}.")

                    connect_response = fabfunc.connect_workspace_to_git(
                        fabric_upn_token, 
                        workspace_id, 
                        git_settings.get("DevOpsOrgName"), 
                        git_settings.get("DevOpsProjectName"),
                        git_settings.get("DevOpsRepoName"),
                        feature_name,
                        stage_props.get("git_folder"))

                    if not connect_response is None:
                        init_response = fabfunc.initialize_workspace_git_connection(fabric_upn_token, workspace.get('id'))
                        if init_response and init_response.get("requiredAction") != "None" and init_response.get("remoteCommitHash"):
                            fabfunc.update_workspace_from_git(fabric_upn_token, workspace.get('id'), init_response["remoteCommitHash"])
            print ("")
        else:
            for stage, stage_props in stages.items():
                workspace_name = dev_env_name.format(feature_name=feature_name.replace("feature/",""), stage=stage)
                feature_workspace = fabfunc.get_workspace_by_name(fabric_access_token, workspace_name)
                if not feature_workspace is None:
                    fabfunc.delete_workspace(fabric_access_token, feature_workspace.get("id"), workspace_name)
                else:
                    print(f"No workspace found matching the feature branch {workspace_name}!")

            devopsfunc.delete_branch(
                devops_token, 
                git_settings.get("DevOpsOrgName"), 
                git_settings.get("DevOpsProjectName"),
                git_settings.get("DevOpsRepoName"),
                feature_name)

duration = datetime.now() - start_time
print(f"Script duration: {duration}")
#endregion