import os, sys, argparse, json
from datetime import datetime

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
sys.path.append(os.getcwd())

import modules.auth_functions as authfunc, modules.azure_functions as azfunc, modules.fabric_functions as fabfunc, modules.devops_functions as devopsfunc

start_time = datetime.now()

parser = argparse.ArgumentParser(description="Fabric solution setup arguments")
parser.add_argument("--action", required=False, default="create", help="Option to create or delete feature and feature workspaces.")
parser.add_argument("--access_token", required=False, default="", help="Microsoft Entra access token with Key Vault scope.")
parser.add_argument("--key_vault", required=False, default="", help="Name of Key Vault resource holding project settings.")
parser.add_argument("--tenant_id", required=False, default="", help="Tenant ID. Used if no key vault/access_token has been passed as parameter.")
parser.add_argument("--app_id", required=False, default="", help="Service Principal Client ID (AppID). Used if no key vault/access_token has been passed as parameter.")
parser.add_argument("--app_secret", required=False, default="", help="Service Principal Client Secret. Used if no key vault/access_token has been passed as parameter.")

args = parser.parse_args()
action = args.action
key_vault_name = args.key_vault
access_token = args.access_token
tenant_id = args.tenant_id
app_id = args.app_id
app_secret = args.app_secret

setup_file_path = os.path.abspath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'environments', 'feature.json')
)

if os.path.exists(setup_file_path):
    with open(setup_file_path, 'r') as file:
        data = json.load(file)
        dev_env_name = data.get("feature_name")
        default_capacity_id = data.get("capacity_id")
        stages = data.get("stages")
        key_vault_name = data.get("key_vault_name")
        spn_id = data.get("spn_managed_identity")
        
if (not access_token is None):
   tenant_id = azfunc.get_keyvault_secret(access_token, key_vault_name, "TenantId")
   app_id = azfunc.get_keyvault_secret(access_token, key_vault_name, "Fabric-SPN-ClientID")
   app_secret = azfunc.get_keyvault_secret(access_token, key_vault_name, "Fabric-SPN-Secret")

fabric_access_token = authfunc.get_access_token(tenant_id, app_id, app_secret, 'https://api.fabric.microsoft.com')
management_token = authfunc.get_access_token(tenant_id, app_id, app_secret, 'https://management.core.windows.net')

org_url = os.getenv("SYSTEM_TEAMFOUNDATIONCOLLECTIONURI")
project_name = os.getenv("SYSTEM_TEAMPROJECT")
repo_name = os.getenv("BUILD_REPOSITORY_NAME")
branch_pathpath = os.getenv("BUILD_SOURCEBRANCH")
branch_name = os.getenv("BUILD_SOURCEBRANCHNAME")
branch_owner_name = os.getenv("BUILD_REQUESTEDFOR")
branch_owner_email = os.getenv("BUILD_REQUESTEDFOREMAIL")
commit_id = os.getenv("BUILD_SOURCEVERSION")

org_name = org_url.split('/')[3]

full_branch_name = branch_pathpath.replace("refs/heads/feature/", "")

if action == "create":
    print(f"############################## Setting up development environment ##############################")
    default_sparksettings = data.get("spark_settings")

    for stage, stage_props in stages.items():
        workspace_name = dev_env_name.format(feature_name=full_branch_name, stage=stage)

        current_time_utc = datetime.now().strftime("%Y-%m-%d %H:%M:%S (UTC)")
        workspace_desc = (
            f"Feature workspace auto-generated by script: {current_time_utc}\n\n"
            f"Organization: {org_name}\n"
            f"Project: {project_name}\n"
            f"Repository: {repo_name}\n"
            f"Branch: {branch_name}\n"
            f"Responsible: {branch_owner_name} ({branch_owner_email})"
        )
        
        feature_workspace = fabfunc.get_workspace_by_name(fabric_access_token, workspace_name)
        if feature_workspace is None:
            workspace = fabfunc.create_workspace(fabric_access_token, workspace_name, workspace_desc)
            workspace_id = workspace.get("id")

            fabfunc.assign_workspace_to_capacity(fabric_access_token, workspace_id, default_capacity_id)
            fabfunc.add_workspace_user(fabric_access_token, workspace_id, "Admin", "User", branch_owner_email)

            spark_settings = stage_props.get("spark_settings", default_sparksettings)
            if spark_settings:
                fabfunc.update_workspace_spark_settings(fabric_access_token, workspace_id, spark_settings, True)

            if stage_props.get("private_endpoints"):
                for private_endpoint in stage_props.get("private_endpoints"):
                    fabfunc.create_workspace_managed_private_endpoint(fabric_access_token, workspace_id, private_endpoint.get("name"), private_endpoint.get("id"))
                    if(private_endpoint.get("auto_approve")):
                        connection_name = f"{workspace_id}.{private_endpoint.get("name")}-"
                        pe_connection = azfunc.get_private_endpoint_by_name(management_token, private_endpoint.get("id"), connection_name)
                        azfunc.approve_private_endpoint(management_token, private_endpoint.get("id"), pe_connection.get("name"))
        else:
            print("A feature workspace already exist! Skipping development environment setup...")
            break
        
        print ("")

else:
    devops_access_token = os.getenv("SYSTEM_ACCESSTOKEN")
    pr_response = devopsfunc.get_pull_request(devops_access_token, org_name, project_name, repo_name, commit_id)
    if not pr_response is None:
        commit_obj = pr_response['results'][0].get(commit_id)
        if commit_obj:
            source_ref_name = commit_obj[0]["sourceRefName"]
            if source_ref_name:
                for stage, stage_props in stages.items():
                    branch_name = source_ref_name.replace('refs/heads/feature/','')
                    workspace_name = dev_env_name.format(feature_name=branch_name, stage=stage)
                    feature_workspace = fabfunc.get_workspace_by_name(fabric_access_token, workspace_name)
                    if not feature_workspace is None:
                        fabfunc.delete_workspace(fabric_access_token, feature_workspace.get("id"), workspace_name)
                    else:
                        print(f"No workspace found matching the feature branch {workspace_name}!")
            else:
                print(f"Not a pull request. Skipping removal of feature workspace for commit id {commit_id}.")
        else:
                print(f"Not a pull request. Skipping removal of feature workspace for commit id {commit_id}.")

duration = datetime.now() - start_time
print(f"Script duration: {duration}")